// Practice test C: 50 original questions weighted like the real Arena exam. Each part of ETCP's
// content outline gets its share (25 of 150 on the exam → about 8 of 50 here; the test checks
// it). The formats copy ETCP's published sample questions: plain four-option items, "which of the
// following" lists answered "1 and 2 only", and put-these-steps-in-order items.
//
// Facts are checked against primary sources, noted beside the question:
//   OSHA     29 CFR 1910 / 1926 on ecfr.gov
//   Crosby   The Crosby Group's catalog and warnings (shackles, clips, wedge sockets, eye bolts)
//   B30.9    ASME B30.9 sling removal criteria; WSTDA RS-1 for round slings
//   Sheet    ETCP's own Rigging Formula Sheet (rev. 01/2010)
//   Handbook ETCP Candidate Handbook, rev. 5.0 (Feb 2016)
// Numbers are recomputed in questions.test.mts.

import type { Question } from "./questions.ts";

export const C: Question[] = [
  // ---- 1A Formulas and forces (9) ----
  { id: "c01", area: "1A", topic: "Object weight", stem: "What total static load do the two rigging points carry?\n• 30 ft truss at 12 lb/ft, hung from two 1-ton chain hoists weighing 140 lb each with chain\n• 12 fixtures at 38 lb each\n• One multicable at 0.6 lb/ft that runs the full length of the truss and then drops 40 ft to the floor", options: ["858 lb", "1,096 lb", "1,114 lb", "1,138 lb"], answer: 3,
    explain: "Truss 30 × 12 = 360. Hoists 2 × 140 = 280. Fixtures 12 × 38 = 456. Cable (30 + 40) × 0.6 = 42. Total = 1,138 lb. The hoists hang from the points, so they count, and so does the cable's drop to the floor; ETCP's own sample question counts both. (858 leaves out the hoists; 1,114 leaves out the drop.)" },
  { id: "c02", area: "1A", topic: "Conversions", stem: "An LED wall is listed at 1.5 metric tonnes. About what does it weigh in pounds?", options: ["1,500 lb", "3,000 lb", "3,307 lb", "3,750 lb"], answer: 2,
    explain: "1 tonne = 1,000 kg, and 1 kg = 2.2046 lb, so 1,500 × 2.2046 ≈ 3,307 lb. (3,000 lb is 1.5 US tons, a different unit.)" },
  { id: "c03", area: "1A", topic: "Conversions", stem: "A cable pick is specified as 15 kg/m. What is that in lb/ft?", options: ["2.07 lb/ft", "10.08 lb/ft", "22.32 lb/ft", "108.49 lb/ft"], answer: 1,
    explain: "Convert the mass up and the length down: 15 kg/m × 2.2046 lb/kg ÷ 3.2808 ft/m ≈ 10.08 lb/ft. Multiplying by both factors (108.49) is the usual slip; a sanity check is that a foot is shorter than a meter, so the lb/ft figure is smaller than the kg/m figure × 2.2." },
  { id: "c04", area: "1A", topic: "Components of force", stem: "A bridle leg carries 2,000 lb and sits 30° from vertical. What is the horizontal component of that force?", options: ["1,000 lb", "1,155 lb", "1,732 lb", "2,000 lb"], answer: 0,
    explain: "Horizontal = T × sin(angle from vertical) = 2,000 × sin 30° = 1,000 lb. The vertical component is 2,000 × cos 30° ≈ 1,732 lb." },
  { id: "c05", area: "1A", topic: "Sling length", stem: "Using the formula sheet's leg length D = √(ΔX² + ΔY² + ΔZ²), how long is a leg whose beam point is 6 ft east, 8 ft north and 24 ft above the apex?", options: ["24.0 ft", "25.3 ft", "26.0 ft", "38.0 ft"], answer: 2,
    explain: "√(6² + 8² + 24²) = √(36 + 64 + 576) = √676 = 26 ft. In 3-D you need all three offsets; 25.3 ft (√(8² + 24²)) forgets one." },
  { id: "c06", area: "1A", topic: "Resultant force", stem: "A hand line runs over a block hung from the steel. The pull on the line is 200 lb and the angle between the two parts of the line at the block is 60°. Using F = P sin a ÷ sin(a/2), what force does the block put on the steel?", options: ["200 lb", "283 lb", "346 lb", "400 lb"], answer: 2,
    explain: "F = 200 × sin 60° ÷ sin 30° = 200 × 0.866 ÷ 0.5 ≈ 346 lb (the same as 2 × 200 × cos 30°). With the lines parallel (0°) it would be the full 400 lb; the wider the angle, the smaller the resultant." },
  { id: "c07", area: "1A", topic: "3-way bridle", stem: "A 3-leg bridle hangs from three points at the same height. In plan, A is at (0, 0), B at (20, 0) and C at (10, 15) ft. The apex is at (10, 5), 12 ft below the points, carrying 2,000 lb. What is the tension in leg A?", options: ["667 lb", "868 lb", "911 lb", "1,000 lb"], answer: 2,
    explain: "The apex sits on the triangle's centroid ((0 + 20 + 10)/3, (0 + 0 + 15)/3) = (10, 5), so the three points share the load equally: 2,000 ÷ 3 ≈ 667 lb vertical each. Leg A: L = √(10² + 5² + 12²) ≈ 16.40 ft, so T = 667 × 16.40 ÷ 12 ≈ 911 lb. (Leg C is 15.62 ft long and carries ≈ 868 lb.)" },
  { id: "c08", area: "1A", topic: "Overhang", stem: "A 300 lb speaker hangs 4 ft beyond point 1 on a short truss supported at point 1 and point 2, 12 ft apart. Ignoring the truss's weight, what happens at each point?", options: ["Point 1: 300 lb; point 2: 0 lb", "Point 1: 400 lb; point 2: 100 lb of uplift", "Point 1: 200 lb; point 2: 100 lb", "Point 1: 400 lb; point 2: 100 lb down"], answer: 1,
    explain: "Take moments about point 1: R₂ = −(300 × 4) ÷ 12 = −100 lb, which is the formula sheet's F₂ = −D₁W ÷ S. The minus sign means point 2 is pulled up. Point 1 then carries 300 + 100 = 400 lb. Uplift can unload a chain hoist completely, so the back point needs enough dead weight (or a tie-down) to stay loaded." },
  { id: "c09", area: "1A", topic: "Shock load", stem: "Which change does the most to reduce the shock load if a load drops before being caught?", options: ["Use a heavier shackle", "Shorten the free-fall distance", "Use a stiffer sling", "Hang it from a longer leg"], answer: 1,
    explain: "F = W × (1 + D_F ÷ D_S). Cutting the free fall (D_F) or lengthening the stopping distance (D_S) lowers the force. A stiffer sling shortens D_S and makes it worse; hardware size doesn't change the force at all." },

  // ---- 1B General principles of rigging (5) ----
  { id: "c10", area: "1B", topic: "Design factor", stem: "A 1/4 in galvanized aircraft cable (7×19, breaking strength 7,000 lb) is being used for an 875 lb load. What design factor is that?", options: ["4:1", "5:1", "8:1", "10:1"], answer: 2,
    explain: "Design factor = breaking strength ÷ load = 7,000 ÷ 875 = 8. That meets the common 8:1 practice for wire rope in entertainment rigging, before any termination efficiency is applied." },
  { id: "c11", area: "1B", topic: "Center of gravity", stem: "A 1,200 lb LED wall hangs from two picks 8 ft apart. Its center of gravity is 2 ft from the left pick. What does the left pick carry?", options: ["300 lb", "600 lb", "900 lb", "1,200 lb"], answer: 2,
    explain: "Left = W × (distance from the CG to the other pick) ÷ spacing = 1,200 × 6 ÷ 8 = 900 lb. The right pick carries 300 lb. The pick closer to the CG always carries more." },
  { id: "c12", area: "1B", topic: "Indeterminate structures", stem: "A continuous truss hangs level from three hoists. If the center hoist is run up a little above the line of the end hoists, what happens?", options: ["Nothing; each hoist still carries a third", "The center hoist takes more load and the end hoists less", "The end hoists take more load and the center less", "Only the total load changes"], answer: 1,
    explain: "With three or more points the load share depends on height. Raising one point makes it pick up load from the others; a low point sheds load. That's why trim matters and why load cells are used on multi-point trusses." },
  { id: "c13", area: "1B", topic: "Fall protection", stem: "A worker's 6 ft shock-absorbing lanyard is anchored at D-ring height. The absorber can deploy up to 3.5 ft, the harness stretch and D-ring shift is 1 ft, the D-ring is 5 ft above the worker's feet, and you add a 2 ft safety margin. How much clear space is needed below the anchor?", options: ["11.5 ft", "15.5 ft", "17.5 ft", "23.5 ft"], answer: 2,
    explain: "Add every part of the fall: 6 (free fall) + 3.5 (deceleration) + 1 (stretch) + 5 (D-ring to feet) + 2 (margin) = 17.5 ft. 3.5 ft is OSHA's limit on deceleration distance (1910.140(d)(1)(ii)). If there isn't that much room, use a self-retracting lifeline or an overhead anchor." },
  { id: "c14", area: "1B", topic: "Fall protection", stem: "Under OSHA, a personal fall arrest system used with a full-body harness must limit the arresting force on the worker to no more than:", options: ["900 lb", "1,800 lb", "3,600 lb", "5,000 lb"], answer: 1,
    explain: "1,800 lb (8 kN): 29 CFR 1910.140(d)(1)(i) and 1926.502(d)(16)(ii). 3,600 lb is the gate strength required of snaphooks and carabiners; 5,000 lb is the anchorage and connector strength." },

  // ---- 1C Drawings and schedules (3) ----
  { id: "c15", area: "1C", topic: "Reading plans", stem: "On a rigging plot drawn at 1/4 in = 1 ft 0 in, two points measure 5-1/2 in apart. How far apart are they?", options: ["5.5 ft", "11 ft", "22 ft", "44 ft"], answer: 2,
    explain: "At 1/4 in to the foot, every inch on the drawing is 4 ft. 5.5 × 4 = 22 ft. Check the scale on every sheet; details are often drawn at a different scale." },
  { id: "c16", area: "1C", topic: "Facility plans", stem: "On a structural steel plan, what does W14×30 tell you about a beam?", options: ["14 in wide flange, 30 ft long", "Wide-flange shape, about 14 in deep, weighing 30 lb per foot", "Wide-flange shape rated for 14,000 lb at 30 ft", "Web 14 mm thick, flange 30 mm wide"], answer: 1,
    explain: "AISC shape designations give the shape (W = wide flange), the nominal depth in inches and the weight in lb/ft. It says nothing about allowable load; that comes from the venue's engineer or rigging guide." },
  { id: "c17", area: "1C", topic: "Building limits", stem: "The venue allows 2,000 lb per point and 6,000 lb total on any one beam. The plot puts four 1,750 lb points on the same beam. What is the right call?", options: ["Fine; every point is under 2,000 lb", "Move at least one point to another beam or redistribute so the beam total is 6,000 lb or less", "Fine if the points are spread at least 4 ft apart", "Add a bridle to each point"], answer: 1,
    explain: "4 × 1,750 = 7,000 lb, which is over the 6,000 lb beam limit even though each point passes. Both limits apply. Moving or bridling to other steel fixes it; bridling on the same beam doesn't reduce the beam total." },

  // ---- 2A Layout and electrical (3) ----
  { id: "c18", area: "2A", topic: "Phasing", stem: "On load-in, every hoist on controller 1 runs in the right direction, but every hoist on controller 2 runs backward. What is the most likely cause?", options: ["Every hoist on controller 2 is wired wrong", "The power feeding controller 2 has reversed phase rotation", "The loads on controller 2 are too light", "The brakes on controller 2's hoists are worn"], answer: 1,
    explain: "When everything on one feed runs backward, look at the feed, not the hoists. Reversed phase rotation is corrected once, by a qualified person at the controller or distribution (many controllers have a phase-reverse switch or indicator), not by rewiring each hoist." },
  { id: "c19", area: "2A", topic: "Power", stem: "Which of the following should be verified before connecting a chain hoist control system to house power?\n1. Voltage\n2. Phase rotation\n3. Rope length\n4. Feeder capacity", options: ["1 and 2 only", "1, 2 and 4 only", "2 and 3 only", "1, 3 and 4 only"], answer: 1,
    explain: "The outline's powered-system items are verify voltage, verify phasing, verify electrical connections, and determine system capacity. Rope length has nothing to do with the power." },
  { id: "c20", area: "2A", topic: "Communication", stem: "What is the best communication setup for a multi-hoist lift?", options: ["Everyone on the general production radio channel", "A dedicated channel, one person calling the moves, and anyone allowed to call stop", "Hand signals only, from the motor operator", "Each up rigger runs their own hoist on their own call"], answer: 1,
    explain: "Establishing communication procedures is part of layout. One voice calls moves on a clear channel, everyone knows the call, and stop can come from anyone who sees a problem." },

  // ---- 2B Rigging attachments (8) ----
  { id: "c21", area: "2B", topic: "Shackles", stem: "A shackle rated 9,500 lb is loaded at 90° to its centerline (side loaded). Per Crosby, what is its reduced working load limit?", options: ["2,375 lb", "4,750 lb", "6,650 lb", "9,500 lb"], answer: 1,
    explain: "Crosby's side-load table: in line 100%, 45° 70%, 90° 50%. 9,500 × 0.5 = 4,750 lb. Better to rig so the shackle is loaded in line." },
  { id: "c22", area: "2B", topic: "Wire rope clips", stem: "Per Crosby's G-450 table, how many clips does a 1/2 in wire rope termination need, and how much turnback?", options: ["2 clips, 6 in", "3 clips, 11-1/2 in", "4 clips, 11-1/2 in", "3 clips, 6 in"], answer: 1,
    explain: "1/2 in rope: minimum 3 clips, 11-1/2 in turnback, 65 ft-lb torque. Saddle on the live end, re-torque after the first load. Always use the manufacturer's table for the clip you have." },
  { id: "c23", area: "2B", topic: "Wedge sockets", stem: "How must a wedge socket be installed?", options: ["Live line in line with the pin; dead end tail clipped to the live line", "Live line in line with the pin; dead end tail clipped to a short piece of rope, never to the live line", "Dead end in line with the pin", "Either line can be in line with the pin if a clip is used"], answer: 1,
    explain: "The live (loaded) line must align with the centerline of the pin, or the wedge rolls and the rope can pull out. Crosby's terminator style clips the dead end to a short added piece of rope; clipping the dead end to the live line is prohibited." },
  { id: "c24", area: "2B", topic: "Knots", stem: "Which knot is tied in the end of a hand line so it can't run out through a block?", options: ["Clove hitch", "Figure 8", "Sheet bend", "Bowline"], answer: 1,
    explain: "A figure 8 stopper is bulky, easy to untie and won't pass through the block. The bowline makes a loop, the sheet bend joins ropes, the clove hitch ties onto a pipe." },
  { id: "c25", area: "2B", topic: "Carabiners", stem: "How should a carabiner be loaded?", options: ["Across the gate (minor axis)", "Along the spine (major axis) with the gate closed and locked", "On the gate, so it stays shut", "In any direction if it's steel"], answer: 1,
    explain: "Carabiners are strongest along the major axis. Cross-loading or gate loading cuts strength drastically. OSHA requires locking connectors that take two deliberate movements to open (1910.140(c)(9))." },
  { id: "c26", area: "2B", topic: "Shackles", stem: "Why is a screw-pin shackle moused (seized with wire) in a permanent or long-term installation?", options: ["To increase its WLL", "To keep the pin from backing out", "To insulate it", "To mark it as inspected"], answer: 1,
    explain: "Vibration and rotation can unscrew a pin. Mousing or using a bolt-type shackle (nut and cotter pin) keeps it captive. It doesn't change the rating." },
  { id: "c27", area: "2B", topic: "Eye bolts", stem: "Per Crosby, a shouldered eye bolt loaded at 45° to its axis keeps what share of its rated load?", options: ["100%", "70%", "50%", "30%"], answer: 3,
    explain: "Crosby's angular-loading table for shouldered eye bolts: 45° → 30%, 90° → 25%, and the shoulder must be seated and the eye in the plane of the pull. Unshouldered (plain) eye bolts are for in-line loads only." },
  { id: "c28", area: "2B", topic: "Secondary safeties", stem: "A moving light is clamped to a truss. What else is required?", options: ["Nothing if the clamp is rated", "A rated secondary safety (safety cable) around the truss and through the fixture's safety point", "Gaffer tape on the clamp", "A second clamp on the same chord"], answer: 1,
    explain: "Anything hung overhead gets a secondary safety that will catch it if the primary attachment fails, attached through the fixture's designated safety point and around the structure." },

  // ---- 2C Operations (9) ----
  { id: "c29", area: "2C", topic: "Lift sequence", stem: "Put these steps for raising a new truss in order.\n1. Bump each hoist to confirm direction and control\n2. Raise in stages, rechecking level\n3. Float the load and inspect the whole assembly\n4. Verify trim", options: ["1, 3, 2, 4", "3, 1, 2, 4", "1, 2, 3, 4", "3, 2, 1, 4"], answer: 0,
    explain: "Bump check first (right hoist, right direction, nothing tight), then float a few inches off the floor and inspect, then raise with periodic level checks, and finally verify trim." },
  { id: "c30", area: "2C", topic: "Load monitoring", stem: "During a lift on four hoists, one load cell drops toward zero while the other three rise. What does it mean?", options: ["That hoist is running faster than the others", "That point has fallen behind (is low) and the others are carrying its share; stop and re-level", "The load cell needs recalibrating; carry on", "The truss has got lighter"], answer: 1,
    explain: "On an indeterminate truss a low point sheds load to the others. Stop, find out why (a slow hoist, a jammed chain, a snag) and re-level before going on." },
  { id: "c31", area: "2C", topic: "Spotters", stem: "What is a spotter's main job during a multi-hoist move?", options: ["Run the controller", "Watch an assigned hoist and its load path and call stop at any problem", "Count the chain links", "Keep the crowd entertained"], answer: 1,
    explain: "Each spotter watches the hoist, the chain feeding into the bag and the path of the load, and calls stop immediately if anything looks wrong." },
  { id: "c32", area: "2C", topic: "Lifting zone", stem: "Who may stand under a load while it's moving?", options: ["Only the spotters", "Only the rigger in charge", "No one", "Anyone wearing a hard hat"], answer: 2,
    explain: "Establish and clear the lifting/lowering zone before any move. A hard hat doesn't make it safe to be under a moving load." },
  { id: "c33", area: "2C", topic: "Leveling", stem: "Why must level be rechecked periodically while raising a truss on several hoists of the same model?", options: ["Hoists of the same model all run at exactly the same speed", "Real hoists run at slightly different speeds, so the truss drifts out of level", "Only to check the chain bags", "It isn't necessary once the bump check is done"], answer: 1,
    explain: "Small speed differences add up over a long run. Out of level shifts load between points on an indeterminate structure. Stop, bump the low points back to level, continue." },
  { id: "c34", area: "2C", topic: "Chain hoists", stem: "Before running a double-reeved chain hoist, you see the hook block has flipped over through the chain. What should you do?", options: ["Run it; the chain will straighten itself", "Stop and correct it so the chain isn't twisted before lifting", "Run it down until the block touches the floor", "Add weight to the hook"], answer: 1,
    explain: "A capsized hook block puts a twist in the chain that can jam the hoist or damage the chain and pockets. Inspect for twists before every lift and correct them per the manufacturer." },
  { id: "c35", area: "2C", topic: "Trim", stem: "What is the best way to verify trim on a truss hanging from four points?", options: ["Count the motor runs", "Measure the height at each pick point from the floor (tape or laser)", "Look at it from front of house", "Use the hoist's chain bag marks"], answer: 1,
    explain: "Measure from the same reference at each point. Eyeballing from a distance hides small differences that shift load on a multi-point truss." },
  { id: "c36", area: "2C", topic: "Controls", stem: "When should the emergency stop function of a hoist control system be tested?", options: ["Only at annual inspection", "As part of the system check before the day's first move", "Only after it has been used in an emergency", "Never; testing it wears it out"], answer: 1,
    explain: "Confirming E-stop operation is part of system commissioning and start-up. It stops all motion and must be deliberately reset; motion never restarts on release." },
  { id: "c37", area: "2C", topic: "Chain bags", stem: "Why must a chain bag be sized for the hoist's full length of chain?", options: ["So the bag carries load", "So chain can't overflow the bag and fall or jam during a long run", "It makes the hoist faster", "So the bag can hold tools"], answer: 1,
    explain: "An undersized bag fills up and spills chain, which can fall on people or pile into the hoist. Check the bag is attached correctly and big enough before running." },

  // ---- 3A Personnel access equipment (3) ----
  { id: "c38", area: "3A", topic: "Aerial lifts", stem: "Working from a boom lift, where must your lanyard be attached?", options: ["To the nearest beam", "To the anchor point on the boom or basket", "To the truss you're working on", "Nowhere; boom lifts have guardrails"], answer: 1,
    explain: "29 CFR 1926.453(b)(2)(v): attached to the boom or basket. Belting off to an adjacent pole, structure or equipment is not permitted (1926.453(b)(2)(iii)), because the basket can move away from it." },
  { id: "c39", area: "3A", topic: "Ladders", stem: "An extension ladder gives access to a landing. How far must its side rails extend above the landing surface?", options: ["12 in", "24 in", "36 in", "48 in"], answer: 2,
    explain: "At least 3 ft, or 36 in (1910.23(c)(11); 1926.1053(b)(1)). In construction OSHA also wants the base about 1/4 of the working length away from the wall (1926.1053(b)(5)(i))." },
  { id: "c40", area: "3A", topic: "Fall protection", stem: "Under OSHA general industry rules, when must fall arrest components (harness, lanyard, connectors) be inspected?", options: ["Once a year", "Before initial use during each workshift", "Only after a fall", "Monthly by the manufacturer"], answer: 1,
    explain: "1910.140(c)(18): inspected before initial use during each workshift. Anything that has arrested a fall comes out of service until a competent person inspects it (1910.140(c)(17))." },

  // ---- 3B Rigging materials (10) ----
  { id: "c41", area: "3B", topic: "Truss", stem: "Where should a truss be picked?", options: ["Anywhere on a diagonal", "At a panel point (node), with the sling around the main chords", "On a single lower chord between nodes", "From the spigot connector"], answer: 1,
    explain: "Truss is designed to take loads at the nodes, where diagonals meet the chords. Picking a diagonal or between nodes bends members they weren't designed to bend. Follow the manufacturer's instructions." },
  { id: "c42", area: "3B", topic: "Truss", stem: "A truss load table lists an allowable uniformly distributed load and an allowable center point load for the same span. How do they compare?", options: ["The center point load is the same as the UDL total", "The center point load is much less than the total UDL", "The center point load is always higher", "They have nothing to do with each other"], answer: 1,
    explain: "A single point load at midspan makes twice the bending moment of the same total spread evenly (WL/4 vs WL/8), so the allowable point load is about half the UDL total or less. Always read the right column." },
  { id: "c43", area: "3B", topic: "Block and fall", stem: "A block and fall has four parts of line supporting the moving block. Ignoring friction, what pull lifts 400 lb?", options: ["50 lb", "100 lb", "200 lb", "400 lb"], answer: 1,
    explain: "Mechanical advantage = parts of line supporting the moving block = 4. 400 ÷ 4 = 100 lb. Real sheaves lose some to friction, so the pull is a bit more." },
  { id: "c44", area: "3B", topic: "Slings", stem: "What tells you the capacity of a round sling?", options: ["Its color", "Its identification tag", "Its length", "Its diameter"], answer: 1,
    explain: "Color coding follows a common chart, but makers vary and colors fade. The tag gives the rated capacity for each hitch. No tag, or an illegible one, means remove it from service (ASME B30.9)." },
  { id: "c45", area: "3B", topic: "Chain", stem: "Which chain may be used in a sling for overhead lifting?", options: ["Grade 30 proof coil", "Grade 43 high test", "Grade 70 transport chain", "Grade 80 or 100 alloy chain"], answer: 3,
    explain: "ASME B30.9 requires alloy chain for chain slings. Proof coil, high test and transport chain are not for overhead lifting." },
  { id: "c46", area: "3B", topic: "Wire rope", stem: "Which of the following call for removing a wire rope sling from service?\n1. Birdcaging\n2. A missing ID tag\n3. Heat damage\n4. A light coat of lubricant", options: ["1 and 3 only", "1, 2 and 3 only", "2 and 4 only", "1, 2, 3 and 4"], answer: 1,
    explain: "ASME B30.9 removal criteria include missing or illegible identification, distortion such as birdcaging, kinking or crushing, heat damage, broken wires beyond limits, and damaged fittings. Lubricant is normal." },
  { id: "c47", area: "3B", topic: "Wire rope", stem: "Compared to a fiber core, an independent wire rope core (IWRC) gives:", options: ["More flexibility and less strength", "More strength and better resistance to crushing", "Lower weight", "No difference"], answer: 1,
    explain: "An IWRC is a small wire rope at the center. It's stronger and holds the strands up better on drums and under crushing loads; a fiber core is a bit more flexible." },
  { id: "c48", area: "3B", topic: "Wire rope", stem: "A sling of 3/16 in galvanized aircraft cable (7×19, breaking strength 4,200 lb) has swaged ends rated at 100% efficiency. What is its WLL at 8:1?", options: ["420 lb", "525 lb", "840 lb", "4,200 lb"], answer: 1,
    explain: "4,200 × 1.00 ÷ 8 = 525 lb. With a termination less than 100% efficient, multiply by its efficiency first." },
  { id: "c49", area: "3B", topic: "Hardware", stem: "Which markings does ASME B30.26 require on a shackle?", options: ["Manufacturer, rated load and size", "Color code and date", "Owner's initials", "Breaking strength only"], answer: 0,
    explain: "Shackles are marked with the manufacturer's name or trademark, the rated load and the size. Unmarked or illegible hardware has no known rating." },
  { id: "c50", area: "3B", topic: "Lever hoists", stem: "A lever hoist won't take up the last of the load by hand. What should you do?", options: ["Slip a pipe over the handle for leverage", "Stop: it's likely overloaded; use a higher-capacity device", "Kick the handle", "Have two people pull the handle"], answer: 1,
    explain: "Manufacturers prohibit cheater bars and extensions. The handle effort is part of how the hoist limits load; if it won't pull, it's over capacity or something is wrong." },
];
