// node studio/camphawk-round2/lqip.mjs  (writes src/lab/camphawk/round2/art-lqip.ts)
// A 16px blurred copy of every round-2 piece, for Art to paint behind the photo while it loads.
import { createRequire } from "node:module";
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const require = createRequire(join(import.meta.dirname, "package.json"));
const sharp = require("sharp");
const ROOT = join(import.meta.dirname, "..", "..");
const dir = join(ROOT, "public/private/camphawk/round2");
const width = (f) => parseInt(f.match(/-(\d+)\.webp$/)[1], 10);
const files = readdirSync(dir).filter((f) => /^[a-z]\d-.*-\d+\.webp$/.test(f));
const names = [...new Set(files.map((f) => f.replace(/-\d+\.webp$/, "")))].sort();

const out = {};
for (const n of names) {
  const smallest = files.filter((f) => f.replace(/-\d+\.webp$/, "") === n).sort((a, b) => width(a) - width(b))[0];
  const buf = await sharp(join(dir, smallest)).resize(16).blur(0.6).webp({ quality: 40 }).toBuffer();
  out[n] = `data:image/webp;base64,${buf.toString("base64")}`;
}

const ts = [
  "// Generated by studio/camphawk-round2/lqip.mjs: a 16px blurred copy of each piece, shown behind",
  "// the photo until it loads, so a slow connection sees the picture's light, not a flat slab.",
  "// Re-run after any re-export.",
  `export const LQIP: Record<string, string> = ${JSON.stringify(out, null, 2)};`,
  "",
].join("\n");
writeFileSync(join(ROOT, "src/lab/camphawk/round2/art-lqip.ts"), ts);
console.log(`${names.length} pieces`);
