// Prompts from docs/design/camphawk-image-prompts.md, tuned per model.
const PHOTO = "bfl/flux-pro-1.1-ultra";
const PAINT = "recraft/recraft-v4.1"; // 1280px max on free credit
const POSTER = "recraft/recraft-v4.1"; // pro tiers are closed to free credit
const PALETTE = "deep pine green #24382A, forest green #1E7A4C, warm ochre #D9932B, pale ochre #FBF0DC, cream #F5F7F2, slate blue #2C4A8A";
const VIGNETTE = `A small vintage WPA-style screen-print vignette on a plain cream (#F5F7F2) background, square, centered, flat layered shapes, gouache texture, palette only ${PALETTE}, no text, no border:`;

export const PROMPTS = {
  "a3-phone-dusk": { model: PHOTO, params: { aspectRatio: "4:5", providerOptions: { blackForestLabs: { raw: true } } }, prompt:
    "A quiet close-up photograph at dusk, looking down at a weathered wooden picnic table. A smartphone lies face up in the lower half of the frame, its blank screen glowing softly white. A pinecone and scattered pine needles lie beside it. Behind the table the background is only tall dark ponderosa pine trunks against a deep blue dusk sky, softly out of focus. A faint warm lantern glow falls on the wood from the left edge. Nothing else in the scene. 35mm film look, Kodak Portra 400, gentle grain, natural color, shallow depth of field." },

  // Round 2.1 (A only): everything in the hero's dusk light, so the page has one light.
  "a3-site-dusk": { model: PHOTO, params: { aspectRatio: "4:5", providerOptions: { blackForestLabs: { raw: true } } }, prompt:
    "A quiet photograph of an empty campsite at dusk in a Sierra Nevada pine forest: a weathered wooden picnic table in the foreground with a glowing brass lantern and an enamel mug on it, a canvas tent softly out of focus behind, tall ponderosa pine trunks, a fading blue sky between the trees. Well exposed blue-hour light, details visible in the shadows, the lantern the one warm light. 35mm film look, Kodak Portra 400, gentle grain, natural color, shallow depth of field. No people, no text, no signs, no logos." },
  "a4-cta-dusk": { model: PHOTO, params: { aspectRatio: "21:9", providerOptions: { blackForestLabs: { raw: true } } }, prompt:
    "A wide, calm photograph of a lakeside campsite at dusk in the Sierra Nevada, just after sunset: still dark-blue water with a thin layer of mist, a granite shoreline, a dark pine treeline on the far shore against a deep blue sky with a faint warm glow at the horizon. In the near left foreground, an enamel camp mug and a small glowing lantern on a flat granite rock. The right half of the frame is calm, dark water and sky with no bright spots, for text. 35mm film look, Kodak Portra 400, gentle grain, natural color. No people, no text, no logos, no sun visible." },
  "a1-hero-wide": { model: PHOTO, params: { aspectRatio: "3:2", providerOptions: { blackForestLabs: { raw: true } } }, prompt:
    "A full-frame landscape photograph, edge to edge with no black bars or borders. Golden hour at a campsite high in the Sierra Nevada: a single canvas bell tent glowing warm from a lantern inside, pitched on a flat granite ledge among tall ponderosa pines. Beyond it, a deep valley of layered blue-green ridges with thin mist, lit by a low sun that is hidden behind the ridge on the right, so the light is soft and diffuse. Warm amber light rakes across the tent and the tree trunks, and the forest shadows are deep pine green. Composition: the glowing tent stands at the right third of the frame. The whole left side of the frame is calm, dark, softly out-of-focus pine trunks in deep shadow, with no bright spots and no sky, for headline text. Shot on 35mm film, Kodak Portra 400, natural color, gentle grain, shallow depth of field. No people, no text, no logos, no cars, no sun visible, no sun rays, no lens flare, not oversaturated." },
  "a2-hero-tall": { model: PHOTO, params: { aspectRatio: "2:3", providerOptions: { blackForestLabs: { raw: true } } }, prompt:
    "A full-frame portrait photograph for a phone screen, edge to edge with no borders: golden hour at a Sierra Nevada campsite, a single canvas bell tent glowing from a lantern on a granite ledge among tall ponderosa pines, a misty valley of layered ridges beyond. The tent sits in the lower third. The upper half is a calm, softly lit sky fading into dark pine silhouettes, with no bright spots, for headline text. 35mm film look, Kodak Portra 400, natural color, gentle grain. No sun visible, no sun rays, no lens flare, no people, no text, no logos." },
  "a3-site-post": { model: PHOTO, params: { aspectRatio: "1:1", providerOptions: { blackForestLabs: { raw: true } } }, prompt:
    "A close, quiet photograph of a bare, weathered, rounded wooden post, plain silver-grey grain, standing at the edge of a pine-forest campsite at blue hour. A picnic table and a dark canvas tent are softly out of focus behind it, and a faint warm lantern glow is in the background. Cool blue light with one small warm accent. 35mm film look, shallow depth of field, natural color. No people, no text anywhere." },
  "a4-cta-morning": { model: PHOTO, params: { aspectRatio: "21:9", providerOptions: { blackForestLabs: { raw: true } } }, prompt:
    "A wide, calm photograph of early morning at a lakeside campsite: mist lifting off still water, granite shoreline, dark pines on the far shore, first warm sunlight touching the treetops. In the near left foreground, an enamel camp mug steams on a flat rock. Most of the frame is soft, quiet water and mist, for text. 35mm film look, soft natural color, gentle grain. No people, no text, no logos." },
  "b1-poster-wide": { model: POSTER, params: { aspectRatio: "3:2" }, prompt:
    `A vintage American national-park travel poster painting, landscape 3:2, in the style of 1930s WPA screen-print posters: flat layered shapes, gouache texture, subtle paper grain, crisp edges. A red-tailed hawk soars in the upper-right of the sky over a granite valley with a winding river. Tall dark pines frame the right edge, and a small canvas tent glows warm beside the river in the lower middle. Layered mountains recede into the distance under a big, flat, calm sky that fills the upper-left half of the image, empty, for a headline. Strictly limited palette: ${PALETTE}. No text, no lettering, no border, no frame, no signature.` },
  "b2-poster-tall": { model: POSTER, params: { aspectRatio: "2:3" }, prompt:
    `A vintage WPA-style national-park poster painting, portrait 2:3: a red-tailed hawk soaring high over a granite valley and a river, tall pines in the lower corners, a small glowing tent by the river at the bottom. The upper half is a big, flat, calm sky, empty, for a headline. Flat layered shapes, gouache texture, subtle paper grain. Palette only: ${PALETTE}. No text, no lettering, no border.` },
  "b3-watch": { model: PAINT, params: { aspectRatio: "1:1" }, prompt: `${VIGNETTE} a brass pocket watch lying open on a pine bough, its hands at 12.` },
  "b4-pack": { model: PAINT, params: { aspectRatio: "1:1" }, prompt: `${VIGNETTE} a canvas backpack with a coiled rope and a tin cup, ready to go.` },
  "b5-map": { model: PAINT, params: { aspectRatio: "1:1" }, prompt: `${VIGNETTE} a folded trail map with a small ochre pin marking a campsite by a lake; no words or numbers on the map.` },
  "b6-calendar": { model: PAINT, params: { aspectRatio: "1:1" }, prompt: `${VIGNETTE} a paper wall calendar whose day squares are blank (no numbers), three of them circled in ochre, beside a lantern.` },
};
